### ISSUE TITLE
build-package.sh fails on fresh Ubuntu Server 16.04 x64

### ISSUE THREAD

**Issue by codise** [spaceify/spaceifyedge#10]
Trying to build spaceify on a fresh install of Ubuntu Server 16.04 x64...

After running `sudo ./data/scripts/install_spaceify_prerequisite.sh`
And then `sudo ./build-package.sh`
error message if presented and package fails to build:
`Building package failed: uglifyMinifyError=127, dpkgBuildpackageError=0`

**Comment by codise** [comment]
Seem like the issue is that `data/scripts/install_spaceify_prerequisite.sh` does not install the command `node` which `/build-package.sh` relies on.

**Comment by ptesavol** [comment]
Thanks for the fix, codise!
